# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Annodoc
baseurl: "/annodoc"
homeurl: "https://plncmm.github.io/annodoc/"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
  finding:
    output: true
  procedure:
    output: true
  relation:
    output: true
  ent_attributes:
    output: true
